### ISSUE TITLE
Incorrect dependency listed on Debian

### ISSUE THREAD

**Issue by hyzchip** [purringChaos/KittehPlayer#24]
In the readme, there appears to be a slight mistake in the list of dependencies for Debian: the package "qtbase5-private" does not exist in the repos.  There is, however, a package called "qtbase5-private-dev".

Anyway, this is a great media player.  It works very well on my PinePhone, with both audio and video files.  Compiling and installing it was quick and easy.  Thank you for creating it!

**Comment by purringChaos** [comment]
Hi thanks! will change.
I think debian changed the package name recently. Will do!
