### ISSUE TITLE
Vaapi(no copy) not work with vo libmpv

### ISSUE THREAD

**Issue by outline941** [purringChaos/KittehPlayer#25]
Vaapi(no copy) not work with vo libmpv.
vaapi-copy worked.
test with `fbo true, direct false` and `fbo false, direct true `

I use `intel_gpu_top` to show if vaapi work.

Other:
only vo=libmpv work with kittehplayer.
other vo will create a separate mpv window

Version:
debian sid
kde 5.17
qt 5.14
mpv 0.31

**Comment by purringChaos** [comment]
You need to use libmpv frontend, correct. 
This is a issue to report upstream probably. Can you see if it is the same in other mpv frontends? 
I am unable to fix this on my end.
vaapi-copy is recommended.
I will be dropping this codebase eventually for a newer one as this is getting too hard to manage.

**Comment by outline941** [comment]
Yes, It's seems like separate mpv window apear when use qml.(test with another qml with libmpv)
