### ISSUE TITLE
Videos not playing on Pinephone

### ISSUE THREAD

**Issue by j0lol** [purringChaos/KittehPlayer#27]
I'm on Manjaro ARM (KDE), whenever KittehPlayer is ran I get this error:
![image](https://user-images.githubusercontent.com/24716467/117585764-082fb400-b10c-11eb-8a2b-29667d3780d3.png)

KittehPlayer will still run, but not display any video.

**Comment by purringChaos** [comment]
kittehplayer at this point is basically discontinued, just use mpv or kodi.
